language: ruby
rvm:
- 2.2.3
env:
- RAILS_ENV=test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp ./.travis.database.yml ./config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- bundle exec rake spec
after_failure:
- psql -e 'show databases;'
- cat ./config/database.yml
- echo $RAILS_ENV
- bundle exec rake --version
branches:
  only: master
after_success:
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  - git remote add production ssh://git@garnet.wdidc.org/home/git/garnet.git
  - git push production
before_install:
- echo -e "Host example.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_91297e33cb51_key -iv $encrypted_91297e33cb51_iv
  -in travis_rsa.enc -out travis_rsa -d
